default:
	javac DLinkedList.java && java DLinkedList

circular:
	javac CLinkedList.java && java CLinkedList

template:
	javac TLinkedList.java && java TLinkedList

int:
	javac IntList.java && java IntList

clean:
	rm -rf *.class