chain:
	javac ChainedHashMap.java && java ChainedHashMap
sorted:
	javac SortedArrayMap.java && java SortedArrayMap
object:
	javac ObjectHashCode.java && java ObjectHashCode
hash:
	javac HashFunctions.java && java HashFunctions
unsorted:
	javac UnsortedArrayMap.java && java UnsortedArrayMap
clean:
	rm -rf *.class