skipmap:
	javac SkipListMap.java && java SkipListMap
skip:
	javac SkipList.java && java SkipList
bhash:
	javac BuiltinHashFunction.java && java BuiltinHashFunction
time:
	javac TimingCompare.java && java TimingCompare
time_pedantic:
	javac -Xlint:unchecked TimingCompare.java && java TimingCompare
chain:
	javac ChainedHashMap.java && java ChainedHashMap
sorted:
	javac SortedArrayMap.java && java SortedArrayMap
object:
	javac ObjectHashCode.java && java ObjectHashCode
hash:
	javac HashFunctions.java && java HashFunctions
unsorted:
	javac UnsortedArrayMap.java && java UnsortedArrayMap
clean:
	rm -rf *.class