test2:
	javac GraphTest2.java && java GraphTest2
graph2:
	javac AdjMapGraph2.java && java AdjMapGraph2
test:
	javac GraphTest.java && java GraphTest
graph:
	javac AdjMapGraph.java && java AdjMapGraph
clean:
	rm -rf *.class