linked:
	javac LinkedQueue.java && java LinkedQueue
deque:
	javac ArrayDeque.java && java ArrayDeque
fixed:
	javac ArrayQueueFS.java && java ArrayQueueFS
queue:
	javac ArrayQueue.java && java ArrayQueue
clean:
	rm -rf *.class