linkedd:
	javac LinkedDeque.java && java LinkedDeque | tee output.LinkedDeque
linkedq:
	javac LinkedQueue.java && java LinkedQueue | tee output.LinkedQueue
arrayd:
	javac ArrayDeque.java && java ArrayDeque | tee output.ArrayDeque
arrayqfs:
	javac ArrayQueueFS.java && java ArrayQueueFS | tee output.ArrayQueueFS
arrayq:
	javac ArrayQueue.java && java ArrayQueue | tee output.ArrayQueue


clean:
	rm -rf *.class 