timing:
	javac Timing.java && java Timing
sorted:
	javac SortedPriorityQueue.java && java SortedPriorityQueue
unsorted:
	javac UnsortedPriorityQueue.java && java UnsortedPriorityQueue
pqb:
	javac PriorityQueueBase.java && java PriorityQueueBase
clean:
	rm -rf *.class
