timing:
	javac Timing.java && java Timing 
max:
	javac MaxOriented.java && java MaxOriented
sorted:
	javac -Xlint:unchecked SortedPQ.java && java SortedPQ
unsorted:
	javac -Xlint:unchecked UnsortedPQ.java && java UnsortedPQ
clean:
	rm -rf *.class