sorted:
	javac SortedPriorityQueue.java && java SortedPriorityQueue
unsorted:
	javac UnsortedPriorityQueue.java && java UnsortedPriorityQueue
pqb:
	javac PriorityQueueBase.java && java PriorityQueueBase
