time:
	javac TreeTiming.java && java TreeTiming > output.txt
test:
	javac TreeTesting.java && java TreeTesting
linked:
	javac -Xlint:unchecked LinkedBinTree.java && java LinkedBinTree
clean:
	rm -rf *.class