game:
	javac PokerGame.java -Xlint:unchecked  && java PokerGame
aces:
	javac CountAces.java -Xlint:unchecked  && java CountAces
hyper:
	javac Hypergeometric.java && java Hypergeometric
binom:
	javac Binomial.java && java Binomial
deck:
	javac Deck.java && java Deck
clean:
	rm -rf *.class