game:
	javac PokerGame.java && java PokerGame
aces:
	javac CountAces.java && java CountAces
hyper:
	javac Hypergeometric.java && java Hypergeometric
binom:
	javac Binomial.java && java Binomial
deck:
	javac Deck.java && java Deck
clean:
	rm -rf *.class