multi:
	javac MultipleDecks.java && java MultipleDecks
deck:
	javac Deck.java && java Deck
game:
	javac PokerGame.java && java PokerGame
solitaire:
	javac Solitaire.java && java Solitaire
aces:
	javac CountAces.java && java CountAces
hyper:
	javac Hypergeometric.java && java Hypergeometric
binom:
	javac Binomial.java && java Binomial
clean:
	rm -rf *.class